src/Entity/Chapitre.php
<?php

namespace App\Entity;

use App\Repository\ChapitreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChapitreRepository::class)]
class Chapitre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $chapitre_title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $chapitre_content = null;

    #[ORM\Column]
    private ?int $chapitre_position = null;

    #[ORM\ManyToOne(inversedBy: 'chapitres')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cours $cours = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChapitreTitle(): ?string
    {
        return $this->chapitre_title;
    }

    public function setChapitreTitle(string $chapitre_title): self
    {
        $this->chapitre_title = $chapitre_title;

        return $this;
    }

    public function getChapitreContent(): ?string
    {
        return $this->chapitre_content;
    }

    public function setChapitreContent(string $chapitre_content): self
    {
        $this->chapitre_content = $chapitre_content;

        return $this;
    }

    public function getChapitrePosition(): ?int
    {
        return $this->chapitre_position;
    }

    public function setChapitrePosition(int $chapitre_position): self
    {
        $this->chapitre_position = $chapitre_position;

        return $this;
    }

    public function getCours(): ?Cours
    {
        return $this->cours;
    }

    public function setCours(?Cours $cours): self
    {
        $this->cours = $cours;

        return $this;
    }
}

src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $cours_title = null;

    #[ORM\Column(length: 100)]
    private ?string $cours_synopsis = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $cours_level = null;

    #[ORM\Column]
    private ?int $cours_duration = null;

    #[ORM\Column(length: 100)]
    private ?string $cours_image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $cours_date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $cours_created = null;

    #[ORM\OneToMany(mappedBy: 'cours', targetEntity: Chapitre::class, orphanRemoval: true)]
    private Collection $chapitres;

    public function __construct()
    {
        $this->chapitres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoursTitle(): ?string
    {
        return $this->cours_title;
    }

    public function setCoursTitle(string $cours_title): self
    {
        $this->cours_title = $cours_title;

        return $this;
    }

    public function getCoursSynopsis(): ?string
    {
        return $this->cours_synopsis;
    }

    public function setCoursSynopsis(string $cours_synopsis): self
    {
        $this->cours_synopsis = $cours_synopsis;

        return $this;
    }

    public function getCoursLevel(): ?int
    {
        return $this->cours_level;
    }

    public function setCoursLevel(int $cours_level): self
    {
        $this->cours_level = $cours_level;

        return $this;
    }

    public function getCoursDuration(): ?int
    {
        return $this->cours_duration;
    }

    public function setCoursDuration(int $cours_duration): self
    {
        $this->cours_duration = $cours_duration;

        return $this;
    }

    public function getCoursImage(): ?string
    {
        return $this->cours_image;
    }

    public function setCoursImage(string $cours_image): self
    {
        $this->cours_image = $cours_image;

        return $this;
    }

    public function getCoursDate(): ?\DateTimeInterface
    {
        return $this->cours_date;
    }

    public function setCoursDate(\DateTimeInterface $cours_date): self
    {
        $this->cours_date = $cours_date;

        return $this;
    }

    public function getCoursCreated(): ?int
    {
        return $this->cours_created;
    }

    public function setCoursCreated(int $cours_created): self
    {
        $this->cours_created = $cours_created;

        return $this;
    }

    /**
     * @return Collection<int, Chapitre>
     */
    public function getChapitres(): Collection
    {
        return $this->chapitres;
    }

    public function addChapitre(Chapitre $chapitre): self
    {
        if (!$this->chapitres->contains($chapitre)) {
            $this->chapitres->add($chapitre);
            $chapitre->setCours($this);
        }

        return $this;
    }

    public function removeChapitre(Chapitre $chapitre): self
    {
        if ($this->chapitres->removeElement($chapitre)) {
            // set the owning side to null (unless already changed)
            if ($chapitre->getCours() === $this) {
                $chapitre->setCours(null);
            }
        }

        return $this;
    }
}

src/Form/CoursType.php
<?php

namespace App\Form;

use App\Entity\Cours;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CoursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cours_title')
            ->add('cours_synopsis')
            ->add('cours_level')
            ->add('cours_duration')
            ->add('cours_image')
            ->add('cours_date')
            ->add('cours_created')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cours::class,
        ]);
    }
}

templates/cours/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CoursController!{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{{ asset('css/cours.css') }}"/>
{% endblock %}

{% block body %}

<div class="head">
    <div class="left-side">
        <h2>{{ cour.coursTitle }}</h2>
        <div class="level">
            <img src="{{ asset('imgs/clock.svg') }}" alt="">
            <span>{{ cour.coursDuration }} heures</span>
            <img src="{{ asset('imgs/level.svg') }}" alt="">
            <span>Niveau {{ cour.coursLevel }}</span>
        </div>
    </div>
    <div class="right-side">
        <img src="{{ asset('imgs/pdf.svg') }}" alt="">
        <span> {{ cour.coursCreated }} </span>
    </div>
</div>

<main>
    
    <div class="progress">
        <span class="dot"><img src="{{ asset('imgs/house.svg') }}" alt="" class="inside-dot"></span>
        <div class="rectangle-line">
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
        </div>
        <div class="rectangle-line">
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
        </div>
        <div class="rectangle-line">
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
            <div class="rectangle"></div>
        </div>              
        <span class="dot"><img src="{{ asset('imgs/certificate.svg') }}" alt="" class="inside-dot"></span>
    </div>
    <pre>
        {{ dump(chapitre) }}
    </pre>

    {# <h2>{{ chapitre.chapitreTitle }}</h2> #}


</main>

                {# <td>{{ chapitre.chapitreContent }}</td>
                <td>{{ chapitre.chapitrePosition }}</td> #}
    
</div>

{% endblock %}