src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CoursRepository::class)]
class Cours
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $cours_title = null;

    #[ORM\Column(length: 100)]
    private ?string $cours_synopsis = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $cours_level = null;

    #[ORM\Column]
    private ?int $cours_duration = null;

    #[ORM\Column(length: 100)]
    private ?string $cours_image = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $cours_date = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $cours_created = null;

    #[ORM\OneToMany(mappedBy: 'cours', targetEntity: Chapitre::class, orphanRemoval: true)]
    private Collection $chapitres;

    public function __construct()
    {
        $this->chapitres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCoursTitle(): ?string
    {
        return $this->cours_title;
    }

    public function setCoursTitle(string $cours_title): self
    {
        $this->cours_title = $cours_title;

        return $this;
    }

    public function getCoursSynopsis(): ?string
    {
        return $this->cours_synopsis;
    }

    public function setCoursSynopsis(string $cours_synopsis): self
    {
        $this->cours_synopsis = $cours_synopsis;

        return $this;
    }

    public function getCoursLevel(): ?int
    {
        return $this->cours_level;
    }

    public function setCoursLevel(int $cours_level): self
    {
        $this->cours_level = $cours_level;

        return $this;
    }

    public function getCoursDuration(): ?int
    {
        return $this->cours_duration;
    }

    public function setCoursDuration(int $cours_duration): self
    {
        $this->cours_duration = $cours_duration;

        return $this;
    }

    public function getCoursImage(): ?string
    {
        return $this->cours_image;
    }

    public function setCoursImage(string $cours_image): self
    {
        $this->cours_image = $cours_image;

        return $this;
    }

    public function getCoursDate(): ?\DateTimeInterface
    {
        return $this->cours_date;
    }

    public function setCoursDate(\DateTimeInterface $cours_date): self
    {
        $this->cours_date = $cours_date;

        return $this;
    }

    public function getCoursCreated(): ?int
    {
        return $this->cours_created;
    }

    public function setCoursCreated(int $cours_created): self
    {
        $this->cours_created = $cours_created;

        return $this;
    }

    /**
     * @return Collection<int, Chapitre>
     */
    public function getChapitres(): Collection
    {
        return $this->chapitres;
    }

    public function addChapitre(Chapitre $chapitre): self
    {
        if (!$this->chapitres->contains($chapitre)) {
            $this->chapitres->add($chapitre);
            $chapitre->setCours($this);
        }

        return $this;
    }

    public function removeChapitre(Chapitre $chapitre): self
    {
        if ($this->chapitres->removeElement($chapitre)) {
            // set the owning side to null (unless already changed)
            if ($chapitre->getCours() === $this) {
                $chapitre->setCours(null);
            }
        }

        return $this;
    }
}

src/Controller/CoursAdminController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Form\CoursType;
use App\Repository\CoursRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/cours/admin')]
class CoursAdminController extends AbstractController
{
    #[Route('/', name: 'app_cours_admin_index', methods: ['GET'])]
    public function index(CoursRepository $coursRepository): Response
    {
        return $this->render('cours_admin/index.html.twig', [
            'cours' => $coursRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_cours_admin_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CoursRepository $coursRepository): Response
    {
        $cour = new Cours();
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $coursRepository->save($cour, true);

            return $this->redirectToRoute('app_cours_admin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cours_admin/new.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_admin_show', methods: ['GET'])]
    public function show(Cours $cour): Response
    {
        return $this->render('cours_admin/show.html.twig', [
            'cour' => $cour,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_cours_admin_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Cours $cour, CoursRepository $coursRepository): Response
    {
        $form = $this->createForm(CoursType::class, $cour);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $coursRepository->save($cour, true);

            return $this->redirectToRoute('app_cours_admin_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cours_admin/edit.html.twig', [
            'cour' => $cour,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_cours_admin_delete', methods: ['POST'])]
    public function delete(Request $request, Cours $cour, CoursRepository $coursRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cour->getId(), $request->request->get('_token'))) {
            $coursRepository->remove($cour, true);
        }

        return $this->redirectToRoute('app_cours_admin_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cours_admin/_delete_form.html.twig
<form method="post" action="{{ path('app_cours_admin_delete', {'id': cour.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cour.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cours_admin/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cours_admin/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cours{% endblock %}

{% block body %}
    <h1>Edit Cours</h1>

    {{ include('cours_admin/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cours_admin_index') }}">back to list</a>

    {{ include('cours_admin/_delete_form.html.twig') }}
{% endblock %}

templates/cours_admin/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours index{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{{ asset('css/crud.css') }}"/>
{% endblock %}

{% block body %}
    <h1>Liste des cours</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Synopsis</th>
                <th>Niveau</th>
                <th>Durée</th>
                <th>Image</th>
                <th>Date</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cour in cours %}
            <tr>
                <td>{{ cour.id }}</td>
                <td>{{ cour.coursTitle }}</td>
                <td>{{ cour.coursSynopsis }}</td>
                <td>{{ cour.coursLevel }}</td>
                <td>{{ cour.coursDuration }}</td>
                <td>{{ cour.coursImage }}</td>
                <td>{{ cour.coursDate ? cour.coursDate|date('Y-m-d') : '' }}</td>
                <td>{{ cour.coursCreated }}</td>
                <td>
                    <a href="{{ path('app_cours_admin_show', {'id': cour.id}) }}">voir</a>
                    <a href="{{ path('app_cours_admin_edit', {'id': cour.id}) }}">modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">aucun résultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_cours_admin_new') }}">Créer un nouveau cours</a>
    <br>
    <a href="{{ path('app_admin_index') }}">Retour à la page admin</a>
{% endblock %}

templates/cours_admin/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cours{% endblock %}

{% block body %}
    <h1>Create new Cours</h1>

    {{ include('cours_admin/_form.html.twig') }}

    <a href="{{ path('app_cours_admin_index') }}">back to list</a>
{% endblock %}

templates/cours_admin/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours{% endblock %}

{% block body %}
    <h1>Cours</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cour.id }}</td>
            </tr>
            <tr>
                <th>Cours_title</th>
                <td>{{ cour.coursTitle }}</td>
            </tr>
            <tr>
                <th>Cours_synopsis</th>
                <td>{{ cour.coursSynopsis }}</td>
            </tr>
            <tr>
                <th>Cours_level</th>
                <td>{{ cour.coursLevel }}</td>
            </tr>
            <tr>
                <th>Cours_duration</th>
                <td>{{ cour.coursDuration }}</td>
            </tr>
            <tr>
                <th>Cours_image</th>
                <td>{{ cour.coursImage }}</td>
            </tr>
            <tr>
                <th>Cours_date</th>
                <td>{{ cour.coursDate ? cour.coursDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Cours_created</th>
                <td>{{ cour.coursCreated }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cours_admin_index') }}">back to list</a>

    <a href="{{ path('app_cours_admin_edit', {'id': cour.id}) }}">edit</a>

    {{ include('cours_admin/_delete_form.html.twig') }}
{% endblock %}